// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'your api key',
    appId: '1:384082262849:web:bac6c1752ad73bbefeffc0',
    messagingSenderId: '384082262849',
    projectId: 'whatsapp-clone-f4adf',
    authDomain: 'whatsapp-clone-f4adf.firebaseapp.com',
    storageBucket: 'whatsapp-clone-f4adf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'your api key',
    appId: '1:384082262849:android:62da0aa1bd8b6bd5feffc0',
    messagingSenderId: '384082262849',
    projectId: 'whatsapp-clone-f4adf',
    storageBucket: 'whatsapp-clone-f4adf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your api key',
    appId: '1:384082262849:ios:6f214b433ababc21feffc0',
    messagingSenderId: '384082262849',
    projectId: 'whatsapp-clone-f4adf',
    storageBucket: 'whatsapp-clone-f4adf.appspot.com',
    iosClientId:
        '384082262849-8oicalfsqqnql7uaaa61cdprejlth7ci.apps.googleusercontent.com',
    iosBundleId: 'kr.co.bepo.flutterWhatsappClone',
  );
}
